### ISSUE TITLE
`ZeroDivisionError` after successful login with Pocket ID

### ISSUE THREAD

**Issue by PaddyPat** [heviat/Mailu-OIDC#39]
### Version

2024.06.7

### Operating System

Linux

### Docker Compose Version

Docker Compose version v2.32.1

### Description

updated docker files from today (so latest update 2024.06.7 is used(

Use PocketID https://github.com/stonith404/pocket-id as auth provider 
(Is fine on 20 other services - so it works) 

After successfull login I  get browser error:

-------
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

-----

mailu.env

```

################################### 
# OpenID Connect settings
###################################

# Enable OpenID Connect. Possible values: True, False
OIDC_ENABLED=True
# OpenID Connect provider configuration URL
OIDC_PROVIDER_INFO_URL=https://pocketid.domainX.com
# OpenID redirect URL if HOSTNAME not matching your login url
#OIDC_REDIRECT_URL=https://mail.domainY.com
# OpenID Connect Client ID for Mailu
OIDC_CLIENT_ID=iddddd
# OpenID Connect Client secret for Mailu
OIDC_CLIENT_SECRET=ssssss
# Label text for OpenID Connect login button. Default: OpenID Connect
OIDC_BUTTON_NAME=OpenID
# Disable TLS certificate verification for the OIDC client. Possible values: True, False
OIDC_VERIFY_SSL=True
# Enable redirect to OIDC provider for password change. Possible values: True, False
#OIDC_CHANGE_PASSWORD_REDIRECT_ENABLED=False
# Redirect URL for password change. Defaults to provider issuer url appended by /.well-known/change-password
#OIDC_CHANGE_PASSWORD_REDIRECT_URL=https://oidc.example.com/pw-change

```

docker logs
```
admin-1      | /app/mailu/models.py:710: SAWarning: fully NULL primary key identity cannot load any object.  This condition may raise an error in a future release.
admin-1      |   return cls.query.get(email)
admin-1      | [2024-12-31 13:09:29,325] WARNING in base: Login failed for None from 10.201.105.1.
admin-1      | [2024-12-31 13:09:29,332] ERROR in app: Exception on /sso/login [GET]
admin-1      | Traceback (most recent call last):
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
admin-1      |     response = self.full_dispatch_request()
admin-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
admin-1      |     rv = self.handle_user_exception(e)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
front-1      | 10.201.105.1 - - [31/Dec/2024:13:09:29 +0000] "GET /sso/login?code=HEyqOezXXXXXXXXXXXXU9xadlbro6&state=pRXXXXXXXXXXX5vP2 HTTP/1.1" 500 265 "https://pocketid.domainX.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
admin-1      |     rv = self.dispatch_request()
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
admin-1      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
admin-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/views/base.py", line 43, in login
admin-1      |     return flask.render_template('login.html', form=form, fields=fields, openId=app.config['OIDC_ENABLED'], openIdEndpoint=utils.oic_client.get_redirect_url())
admin-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
admin-1      |     return _render(app, template, context)
admin-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
admin-1      |     rv = template.render(context)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
admin-1      |     self.environment.handle_exception()
admin-1      |   File "/app/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
admin-1      |     raise rewrite_traceback_stack(source=source)
admin-1      |   File "/app/mailu/sso/templates/login.html", line 1, in top-level template code
admin-1      |     {%- extends "form_sso.html" %}
admin-1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/templates/form_sso.html", line 1, in top-level template code
admin-1      |     {%- extends "base_sso.html" %}
admin-1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/templates/base_sso.html", line 70, in top-level template code
admin-1      |     {%- block content %}{%- endblock %}
admin-1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/templates/form_sso.html", line 4, in block 'content'
admin-1      |     {%- call macros.card() %}
admin-1      |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1      |     rv = self._func(*arguments)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/ui/templates/macros.html", line 83, in template
admin-1      |     {{- caller() }}
admin-1      |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1      |     rv = self._func(*arguments)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/templates/form_sso.html", line 9, in template
admin-1      |     {{ macros.form_fields(fields, label=False, class="btn btn-default") }}
admin-1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1      |     rv = self._func(*arguments)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/ui/templates/macros.html", line 22, in template
admin-1      |     {%- set width = (12 / fields|length)|int %}
admin-1      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      | ZeroDivisionError: division by zero
antispam-1   | 2024-12-31 13:09:29 #170(hs_helper) rspamd_rs_compile_cb: compiled 0 regular expressions to the hyperscan tree, postpone loaded notification for 1 seconds to avoid races
antispam-1   | 2024-12-31 13:09:30 #169(controller) <nnw8jx>; map; http_map_finish: need to reread map from http://admin:8080/internal/rspamd/local_domains
antispam-1   | 2024-12-31 13:09:30 #169(controller) <nnw8jx>; map; http_map_finish: need to reread map from http://admin:8080/internal/rspamd/local_domains
antispam-1   | 2024-12-31 13:09:30 #1(main) <cd8e0b>; main; rspamd_srv_handler: received hyperscan cache loaded from /var/lib/rspamd/
antispam-1   | 2024-12-31 13:09:35 #169(controller) <nnw8jx>; map; http_map_finish: stored map data in a shared memory cache: /rhm.a379ff20c7ef57d56882
antispam-1   | 2024-12-31 13:09:35 #169(controller) <nnw8jx>; map; http_map_finish: http://admin:8080/internal/rspamd/local_domains(10.201.105.4:8080): read map data 16 bytes, next check at Tue, 31 Dec 2024 13:14:35 GMT
```

### Replication Steps

-

### Observed Behaviour

-

### Expected Behaviour

-

### Relevant log output

```shell
admin-1      | /app/mailu/models.py:710: SAWarning: fully NULL primary key identity cannot load any object.  This condition may raise an error in a future release.
admin-1      |   return cls.query.get(email)
admin-1      | [2024-12-31 13:09:29,325] WARNING in base: Login failed for None from 10.210.100.1.
admin-1      | [2024-12-31 13:09:29,332] ERROR in app: Exception on /sso/login [GET]
```

**Comment by Wombosvideo** [comment]
This looks a lot like https://github.com/Mailu/Mailu/issues/2155. We will look into it.

**Comment by Wombosvideo** [comment]
Try changing `OIDC_PROVIDER_INFO_URL` to `https://pocketid.domainX.com/.well-known/openid-configuration` in your `mailu.env`.

- Check the [example in the `README.md`](https://github.com/heviat/Mailu-OIDC?tab=readme-ov-file#setting-up-variables)
- Also see the [pocket-id source code](https://github.com/stonith404/pocket-id/blob/204313aacf901b804e86a286cbcdf10e20b47404/backend/internal/controller/well_known_controller.go#L13)

**Comment by murdantix** [comment]
I have the same issue and i could not fix it

**Comment by Wombosvideo** [comment]
> I have the same issue and i could not fix it

Are you also using PocketID?

**Comment by murdantix** [comment]
No, i am using Shibboleth 5.1

**Comment by daniel-ratz** [comment]
Hi. Just deployed mailu-oidc using authentik and i have the same problem. OIDC Login works but then i'll error get error 500 with almost the same error message:
`admin-1     | [2025-01-20 16:40:32,425] WARNING in base: Login failed for None from <IP>.
admin-1     | [2025-01-20 16:40:32,432] ERROR in app: Exception on /sso/login [GET]
admin-1     | Traceback (most recent call last):
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
admin-1     |     response = self.full_dispatch_request()
admin-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
admin-1     |     rv = self.handle_user_exception(e)
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
admin-1     |     rv = self.dispatch_request()
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
admin-1     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
admin-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/sso/views/base.py", line 43, in login
admin-1     |     return flask.render_template('login.html', form=form, fields=fields, openId=app.config['OIDC_ENABLED'], openIdEndpoint=utils.oic_client.get_redirect_url())
admin-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
admin-1     |     return _render(app, template, context)
admin-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
admin-1     |     rv = template.render(context)
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
admin-1     |     self.environment.handle_exception()
admin-1     |   File "/app/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
admin-1     |     raise rewrite_traceback_stack(source=source)
admin-1     |   File "/app/mailu/sso/templates/login.html", line 1, in top-level template code
admin-1     |     {%- extends "form_sso.html" %}
admin-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/sso/templates/form_sso.html", line 1, in top-level template code
admin-1     |     {%- extends "base_sso.html" %}
admin-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/sso/templates/base_sso.html", line 70, in top-level template code
admin-1     |     {%- block content %}{%- endblock %}
admin-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/sso/templates/form_sso.html", line 4, in block 'content'
admin-1     |     {%- call macros.card() %}
admin-1     |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1     |     rv = self._func(*arguments)
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/ui/templates/macros.html", line 83, in template
admin-1     |     {{- caller() }}
admin-1     |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1     |     rv = self._func(*arguments)
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/sso/templates/form_sso.html", line 9, in template
admin-1     |     {{ macros.form_fields(fields, label=False, class="btn btn-default") }}
admin-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/venv/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
admin-1     |     rv = self._func(*arguments)
admin-1     |          ^^^^^^^^^^^^^^^^^^^^^^
admin-1     |   File "/app/mailu/ui/templates/macros.html", line 22, in template
admin-1     |     {%- set width = (12 / fields|length)|int %}
admin-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1     | ZeroDivisionError: division by zero`

i also tried to set the rate limits higher, they're at 999 right now - same problem. Any ideas?

**Comment by Encotric** [comment]
Hi, seems like we've missed some changes of the Mailu upstream repository. Should be fixed now.

**Comment by PaddyPat** [comment]
hi, it isn't.. 

there is a new message in webui during login:

"Wrong e-mail or password"

created mailbox before, doesn't work.

with

"Try changing OIDC_PROVIDER_INFO_URL to https://pocketid.domainX.com/.well-known/openid-configuration in your mailu.env." mailu doesn't start, works only with https://pocketid.domainX.com
